name: "bohr-io"
description: "Deploy your repository on bohr.io"
branding:
  icon: chevron-up
  color: orange
inputs:
  cli-version:
    description: "Optional CLI version"
    required: false
runs:
  using: "composite"
  steps:
    - name: Deploy on bohr.io using NPM
      run: |
        npx --yes bohr@latest deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
        FORCE_COLOR: "2"
      if: ${{ inputs.cli-version == null }}
      shell: bash

    - name: Deploy on bohr.io [${{ inputs.cli-version }}]
      run: |
        npx --yes ${{ inputs.cli-version }} deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
        FORCE_COLOR: "2"
      shell: bash
      if: ${{ inputs.cli-version != null }}
